#ifndef _BOARDS_DEVBOARD_BOARD_CONFIG_H
#define _BOARDS_DEVBOARD_BOARD_CONFIG_H

#define BOARD_NAME "devboard"
#define MCU_NAME "RTL8762C"

#define BOARD_TX_PAD (P3_0)
#define BOARD_RX_PAD (P3_1)

#define LED_PAD (P0_6)

#endif // _BOARDS_DEVBOARD_BOARD_CONFIG_H
