/**
*****************************************************************************************
*     Copyright(c) 2017, Realtek Semiconductor Corporation. All rights reserved.
*****************************************************************************************
* @file    flash_map.h
* @brief   Flash Layout Configuration, and flash layout must be changed with
*config file!
* @note    flash_map.h must be generated by FlashMapGenerateTool!
* *************************************************************************************
*/

#ifndef _FLASH_MAP_H_
#define _FLASH_MAP_H_

#ifdef __cplusplus
extern "C" {
#endif

/*============================================================================*
 *                        Flash Layout
 *============================================================================*/
/*  Flash total size                                512KB
example:
        1) Reaerved:                                       4K (0x00800000)
        2) OEM Header:                                     4K (0x00801000)
        3) OTA Bank0:                                    148K (0x00802000)
                a) OTA Header                    4K (0x00802000)
                b) Secure boot loader            4K (0x0080D000)
                c) Patch code                   40K (0x00803000)
                d) APP code                    100K (0x0080E000)
                e) APP data1                     0K (0x00827000)
                f) APP data2                     0K (0x00827000)
                e) APP data3                     0K (0x00827000)
                f) APP data4                     0K (0x00827000)
                e) APP data5                     0K (0x00827000)
                f) APP data6                     0K (0x00827000)
        4) OTA Bank1:                                      0K (0x00827000)
                a) OTA Header                    0K (0x00000000)
                b) Secure boot loader            0K (0x00000000)
                c) Patch code                    0K (0x00000000)
                d) APP code                      0K (0x00000000)
                e) APP data1                     0K (0x00000000)
                f) APP data2                     0K (0x00000000)
                f) APP data3                     0K (0x00000000)
                f) APP data4                     0K (0x00000000)
                f) APP data5                     0K (0x00000000)
                f) APP data6                     0K (0x00000000)
        5) FTL:                                           16K (0x00827000)
        6) OTA Tmp:                                      100K (0x0082B000)
        7) APP Defined Section:                          240K (0x00844000)
*/

/*============================================================================*
 *            Flash Layout Configuration (Generated by FlashMapGenerateTool)
 *============================================================================*/

#define FLASH_ADDR 0x00800000 // Fixed

/* ========== High Level Flash Layout Configuration ========== */
#define RESERVED_ADDR (FLASH_ADDR)
#define RESERVED_SIZE 0x00001000 // 4K Bytes
#define OEM_CFG_ADDR (RESERVED_ADDR + RESERVED_SIZE)
#define OEM_CFG_SIZE 0x00001000 // 4K Bytes
#define OTA_BANK0_ADDR (OEM_CFG_ADDR + OEM_CFG_SIZE)

/* ========== OTA Bank0 Flash Layout Configuration ========== */
#define BANK0_OTA_HEADER_ADDR (OTA_BANK0_ADDR)
#define BANK0_OTA_HEADER_SIZE 0x00001000 // 4K Bytes
#define BANK0_ROM_PATCH_ADDR (BANK0_OTA_HEADER_ADDR + BANK0_OTA_HEADER_SIZE)
#define BANK0_ROM_PATCH_SIZE 0x0000A000 // 40K Bytes
#define BANK0_SECURE_BOOT_ADDR (BANK0_ROM_PATCH_ADDR + BANK0_ROM_PATCH_SIZE)
#define BANK0_SECURE_BOOT_SIZE 0x00001000 // 4K Bytes
#define BANK0_APP_ADDR (BANK0_SECURE_BOOT_ADDR + BANK0_SECURE_BOOT_SIZE)
#define BANK0_APP_SIZE (FIRMWARE_SIZE)
#define BANK0_APP_DATA1_ADDR (BANK0_APP_ADDR + BANK0_APP_SIZE)
#define BANK0_APP_DATA1_SIZE 0x00000000 // 0K Bytes
#define BANK0_APP_DATA2_ADDR (BANK0_APP_DATA1_ADDR + BANK0_APP_DATA1_SIZE)
#define BANK0_APP_DATA2_SIZE 0x00000000 // 0K Bytes
#define BANK0_APP_DATA3_ADDR (BANK0_APP_DATA2_ADDR + BANK0_APP_DATA2_SIZE)
#define BANK0_APP_DATA3_SIZE 0x00000000 // 0K Bytes
#define BANK0_APP_DATA4_ADDR (BANK0_APP_DATA3_ADDR + BANK0_APP_DATA3_SIZE)
#define BANK0_APP_DATA4_SIZE 0x00000000 // 0K Bytes
#define BANK0_APP_DATA5_ADDR (BANK0_APP_DATA4_ADDR + BANK0_APP_DATA4_SIZE)
#define BANK0_APP_DATA5_SIZE 0x00000000 // 0K Bytes
#define BANK0_APP_DATA6_ADDR (BANK0_APP_DATA5_ADDR + BANK0_APP_DATA5_SIZE)
#define BANK0_APP_DATA6_SIZE 0x00000000 // 0K Bytes

/* ========== High Level Flash Layout Configuration ========== */
#define OTA_BANK0_SIZE (BANK0_OTA_HEADER_SIZE \
                      + BANK0_SECURE_BOOT_SIZE \
                      + BANK0_ROM_PATCH_SIZE \
                      + BANK0_APP_SIZE \
                      + BANK0_APP_DATA1_SIZE \
                      + BANK0_APP_DATA2_SIZE \
                      + BANK0_APP_DATA3_SIZE \
                      + BANK0_APP_DATA4_SIZE \
                      + BANK0_APP_DATA5_SIZE \
                      + BANK0_APP_DATA6_SIZE \
                      ) // 148K Bytes
#define OTA_BANK1_ADDR (OTA_BANK0_ADDR + OTA_BANK0_SIZE)

/* ========== OTA Bank1 Flash Layout Configuration ========== */
#define BANK1_OTA_HEADER_ADDR (OTA_BANK1_ADDR)
#define BANK1_OTA_HEADER_SIZE 0x00000000 // 0K Bytes
#define BANK1_SECURE_BOOT_ADDR (BANK1_OTA_HEADER_ADDR + BANK1_OTA_HEADER_SIZE)
#define BANK1_SECURE_BOOT_SIZE 0x00000000 // 0K Bytes
#define BANK1_ROM_PATCH_ADDR (BANK1_SECURE_BOOT_ADDR + BANK1_SECURE_BOOT_SIZE)
#define BANK1_ROM_PATCH_SIZE 0x00000000 // 0K Bytes
#define BANK1_APP_ADDR (BANK1_ROM_PATCH_ADDR + BANK1_ROM_PATCH_SIZE)
#define BANK1_APP_SIZE 0x00000000 // 0K Bytes
#define BANK1_APP_DATA1_ADDR (BANK1_APP_ADDR + BANK1_APP_SIZE)
#define BANK1_APP_DATA1_SIZE 0x00000000 // 0K Bytes
#define BANK1_APP_DATA2_ADDR (BANK1_APP_DATA1_ADDR+BANK1_APP_DATA1_SIZE)
#define BANK1_APP_DATA2_SIZE 0x00000000 // 0K Bytes
#define BANK1_APP_DATA3_ADDR (BANK1_APP_DATA2_ADDR + BANK1_APP_DATA2_SIZE)
#define BANK1_APP_DATA3_SIZE 0x00000000 // 0K Bytes
#define BANK1_APP_DATA4_ADDR (BANK1_APP_DATA3_ADDR + BANK1_APP_DATA3_SIZE)
#define BANK1_APP_DATA4_SIZE 0x00000000 // 0K Bytes
#define BANK1_APP_DATA5_ADDR (BANK1_APP_DATA4_ADDR + BANK1_APP_DATA4_SIZE)
#define BANK1_APP_DATA5_SIZE 0x00000000 // 0K Bytes
#define BANK1_APP_DATA6_ADDR (BANK1_APP_DATA5_ADDR + BANK1_APP_DATA5_SIZE)
#define BANK1_APP_DATA6_SIZE 0x00000000 // 0K Bytes

/* ========== High Level Flash Layout Configuration ========== */
#define OTA_BANK1_SIZE (BANK1_OTA_HEADER_SIZE \
                      + BANK1_SECURE_BOOT_SIZE \
                      + BANK1_ROM_PATCH_SIZE \
                      + BANK1_APP_SIZE \
                      + BANK1_APP_DATA1_SIZE \
                      + BANK1_APP_DATA2_SIZE \
                      + BANK1_APP_DATA3_SIZE \
                      + BANK1_APP_DATA4_SIZE \
                      + BANK1_APP_DATA5_SIZE \
                      + BANK1_APP_DATA6_SIZE \
                      ) // 0K Bytes
#define FTL_ADDR (OTA_BANK1_ADDR + OTA_BANK1_SIZE)
#define FTL_SIZE 0x00004000 // 16K Bytes
#define OTA_TMP_ADDR (FTL_ADDR + FTL_SIZE)
#define OTA_TMP_SIZE (BANK0_APP_SIZE) // 100K Bytes
#define BKP_DATA1_ADDR (OTA_TMP_ADDR + OTA_TMP_SIZE)
#define BKP_DATA1_SIZE (FLASH_ADDR + FLASH_SIZE - BKP_DATA1_ADDR) // 240K Bytes
#define BKP_DATA2_ADDR 0x00000000
#define BKP_DATA2_SIZE 0x00000000 // 0K Bytes

#ifdef __cplusplus
}
#endif
/** @} */ /* _FLASH_MAP_H_ */
#endif
